src/databases/models/Contests.ts
src/error/error-message.ts
src/routers/content-router.ts
src/routers/index.ts
src/services/contest-service.ts
src/types/index.ts
src/types/pagination-result.ts

- pagination 유틸을 적용했을 때 반환 타입을 수동으로 작성해야 함
- PaginationResult<T> 타입 구현
- 학생협업공모전 관련 로직 및 API 구현
- 관련 DB Model 구현

feat: 학생협업공모전 API 구현

---

src/databases/association.ts

- Users, Contests 테이블 간의 관계 설정이 되어있지 않습니다.
- 두 테이블을 1:1 관계로 설정하였습니다.

feat: DB 관계 설정 코드 추가

---

src/auth/index.ts
yarn.lock

fix: passport 타입 오류 임시 해결

---

src/services/activation-code-service.ts

- 인증코드 관리 시 id 정렬이 되지 않는 문제
- id 기준으로 오름차순 정렬

feat: id 정렬 조건 추가

---

Dockerfile
src/error/error-message.ts
src/routers/content-router.ts
src/routers/umbrella/umbrella-router.ts

- 수정과 QR코드가 아닌 다른 것을 스캔하면 오류가 발생합니다.
- 유효한 QR코드가 아니면 오류를 반환합니다.
- 일부 HTTP Status Code를 API에 어울리는 코드로 변경했습니다.
- 백엔드에서 vi(m) 사용을 위해 Dockerfile을 업데이트 했습니다.

fix: QR코드 유효성 체크 추가

---

src/routers/notice-router.ts

feat: 공지사항수정한API제작

---

package.json
src/cache/api-cache.ts
yarn.lock

- 기존 미세먼지 API 종료 및 교체
- 미세먼지 API 수정

fix: 미세먼지 API 수정

---

src/services/activation-code-service.ts
src/services/auth-service.ts
src/services/contest-service.ts
src/services/school/timetable-service.ts
src/services/umbrella-service.ts
src/services/uniform-service.ts
src/utils/router-util.ts

- `pagination()` 리펙토링
- 반환 타입 적용
- 파라미터 Optional 삭제
- `filter()` 구현 (search() 대체)
- `order()` 구현
- `filter()` 사용 시 where 옵션 안에서 사용

refactor: pagination() 리팩토링 및 filter() order() 구현

---

Dockerfile
README.md

- Dockerfile 내 apt 명령어를 apt-get 명령어로 수정

chore: apt-get으로 명령어 수정

---

Dockerfile
src/cron.ts

- 자동 탈퇴 시 관리자, 선생님은 제외하도록 수정
- 불필요한 import code, logger 삭제
- 더 이상 vim을 사용하지 않아 이미지 빌드 시 vim 설치 코드 삭제

fix: 자동 탈퇴 시 관리자, 선생님은 제외하도록 수정

---

apidoc.json
package.json
src/config.ts
src/index.ts
src/routers/activation-code-router.ts
src/routers/auth-router.ts
src/routers/notice-router.ts
src/routers/qr-router.ts
src/routers/school-router.ts
src/routers/timetable-router.ts
src/routers/umbrella/umbrella-getter-router.ts
src/routers/umbrella/umbrella-router.ts
src/routers/weather-router.ts
yarn.lock

- 기존 apidoc에서 Swagger로 변경하였습니다.
- Contest(레거시 예정), Uniform(레거시) 경우 문서화가 되어있지 않습니다.

chore: Swagger API 문서 적용

---

.eslintrc.js
src/cron.ts
src/middlewares/permission.ts
src/routers/auth-router.ts
src/routers/qr-router.ts
src/routers/timetable-router.ts
src/routers/umbrella/umbrella-router.ts
src/services/umbrella-service.ts

- 3학년 탈퇴일 변경 (3월 2일 -> 2월 28일)
-  Return, Variable Type 재정의
- ESLint 룰 변경 및 적용
- 불필요한 any 타입 수정

fix: 3학년 탈퇴일 변경

---

src/routers/timetable-router.ts
src/services/school/timetable-service.ts

- 백엔드 페이지 파라미터가 offset으로 되어있는 오류 수정 (page로 변경)
- 시간표 과목내에서 특수문자는 걸러지도록 수정
- 불필요한 과목 이름은 걸러지도록 수정

fix: 시간표 관련 오류 수정

---

src/routers/umbrella/umbrella-router.ts

- 기존 우산 반납 시간 오타 수정
- 반납 시간 오후 6시로 변경

fix: 우산 반납 시간 변경 (6시)

---

src/cron.ts
src/services/fcm-service.ts

feat: 자가진단 바로가기 이벤트 추가

---

src/routers/timetable-router.ts

fix:  시간표 요청 시 올바른 학년, 반만 받도록 수정

---

bin/pickEvent.ts
package.json

feat: implement pick command for event

---

src/index.ts
src/routers/fcm-router.ts

- /fcm에서 /fcm/token 으로 변경
- 오류 발생 시 `production` 환경에서만 알림을 보내도록 수정
- FCM Token 등록 또는 업데이트를 위해 /fcm/token을 사용해야 합니다.

fix: FCM 토큰 등록, 업데이트 path 수정 및 오류 알림 개선

---

src/databases/association.ts
src/databases/models/anonymous-reply.ts
src/databases/models/anonymous.ts
src/error/error-message.ts
src/routers/anonymous-router.ts
src/routers/index.ts
src/services/anonymous-service.ts

- 익명 건의함 API를 구현했습니다.
- 전체 익명 건의 가져오기
- ID로 특정 익명 건의 가져오기
- 익명 건의 올리기
- 익명 건의에 답변 올리기
- 답변 수정하기
- 답변 삭제하기
- 답변 수정과 삭제는 자기자신만 사용 가능합니다. (로그인 정보 기준으로 체크)
- 자세한 API 내용은 Swagger 참고해주세요.

feat: 익명 건의함 API 구현

---

.gitignore
src/routers/anonymous-router.ts

- GET `/reply/{id}` 를 통해 reply id로 답변을 가져올 수 있습니다.

feat: 익명 건의 답변 가져오는 API 구현

---

src/routers/anonymous-router.ts

chore: update dependency

---

src/cache/calendar.cache.ts
src/services/school/calendar-service.ts
src/utils/date-util.ts

학사일정이 다음달로 넘어갈때 일정이 제대로 나오지 않는것을 수정했습니다

fix: AcademicSchedule

---

.gitignore
src/routers/anonymous-router.ts

- 학사일정에서 이번달, 다음달을 동시에 불러올 때 잘못된 일정이 나오는 오류 수정 (#58)

fix: 학사일정 불러오는 로직 수정

---

Dockerfile
src/services/school/meal-service.ts

- 다음날 급식임에도 불구하고 오늘 급식이 나오는 문제 해결

HOTFIX: 다음날 급식 못 불러오는 오류 수정

---

Dockerfile

- docker 빌드 시 playwright 의존성 설치

HOTFIX: playwright 의존성 추가

---

src/utils/date-util.ts

fix: 날짜 오류 수정

---

src/routers/subject/application-subject-router.ts

HOTFIX: /application/config 접근 권한 변경

---

src/services/subject/application-subject-service.ts

- 1지망이 있음에도 2지망이 먼저 추첨되는 오류 수정

fix: 추첨 시 우선순위를 고려하도록 변경
